-------------------Log----------------24/05/02-10:02:32
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\users.py", line 141, in login
    if not check_exist(username):
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\inetpub\wwwroot\WEB_DATA_API\users.py", line 20, in check_exist
    conn = pyodbc.connect('Driver={SQL Server}; Server=192.168.8.21; uid=sa; pwd=1234; Database=QC; Trusted_Connection=No;', timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC SQL Server Driver]Login timeout expired (0) (SQLDriverConnect)')
 ---- login