-------------------Log----------------24/04/22-16:05:54
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 2273, in search_data_5
    conn = pyodbc.connect('Driver={SQL Server}; Server=192.168.8.21; uid=sa; pwd=1234;Database=QC; Trusted_Connection=No;',timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC SQL Server Driver]Login timeout expired (0) (SQLDriverConnect)')
 ---- search_data_5
-------------------Log----------------24/04/22-16:44:14
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 2416, in search_data_6
    'timeCheck': datetime.strptime(time_check, '%a, %d %b %Y %H:%M:%S %Z').strftime('%Y-%m-%d %H:%M:%S'),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not datetime.datetime
 ---- search_data_6
-------------------Log----------------24/04/22-16:44:15
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 2321, in search_data_5
    'timeStart': datetime.strptime(time_start_air_tight, '%a, %d %b %Y %H:%M:%S %Z').strftime('%Y-%m-%d %H:%M:%S'),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not datetime.datetime
 ---- search_data_5
-------------------Log----------------24/04/22-16:44:15
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 2230, in search_data_4
    'timeScanDMC': datetime.strptime(time_scan_dmc, '%a, %d %b %Y %H:%M:%S %Z').strftime('%Y-%m-%d %H:%M:%S'),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not datetime.datetime
 ---- search_data_4
-------------------Log----------------24/04/22-16:44:15
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 2136, in search_data_3
    'timeInOP1': datetime.strptime(time_in_op1, '%a, %d %b %Y %H:%M:%S %Z').strftime('%Y-%m-%d %H:%M:%S'),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not datetime.datetime
 ---- search_data_3
-------------------Log----------------24/04/22-16:44:17
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 1967, in search_data_2
    'timeScanProduct': datetime.strptime(time_scan_product, '%a, %d %b %Y %H:%M:%S %Z').strftime('%Y-%m-%d %H:%M:%S'),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not datetime.datetime
 ---- search_data_2
-------------------Log----------------24/04/22-16:44:19
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 1839, in search_data_1
    'datetimeCreate': datetime.strptime(datetime_create, '%a, %d %b %Y %H:%M:%S %Z').strftime('%Y-%m-%d %H:%M:%S'),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not datetime.datetime
 ---- search_data_1
-------------------Log----------------24/04/22-16:49:24
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 2416, in search_data_6
    'timeCheck': datetime.strptime(time_check, '%a, %d %b %Y %H:%M:%S %Z').strftime('%Y-%m-%d %H:%M:%S'),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not datetime.datetime
 ---- search_data_6
-------------------Log----------------24/04/22-16:49:25
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 2321, in search_data_5
    'timeStart': datetime.strptime(time_start_air_tight, '%a, %d %b %Y %H:%M:%S %Z').strftime('%Y-%m-%d %H:%M:%S'),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not datetime.datetime
 ---- search_data_5
-------------------Log----------------24/04/22-16:49:25
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 2230, in search_data_4
    'timeScanDMC': datetime.strptime(time_scan_dmc, '%a, %d %b %Y %H:%M:%S %Z').strftime('%Y-%m-%d %H:%M:%S'),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not datetime.datetime
 ---- search_data_4
-------------------Log----------------24/04/22-16:49:26
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 2136, in search_data_3
    'timeInOP1': datetime.strptime(time_in_op1, '%a, %d %b %Y %H:%M:%S %Z').strftime('%Y-%m-%d %H:%M:%S'),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not datetime.datetime
 ---- search_data_3
-------------------Log----------------24/04/22-16:49:27
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 1967, in search_data_2
    'timeScanProduct': datetime.strptime(time_scan_product, '%a, %d %b %Y %H:%M:%S %Z').strftime('%Y-%m-%d %H:%M:%S'),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not datetime.datetime
 ---- search_data_2
-------------------Log----------------24/04/22-16:49:35
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 1839, in search_data_1
    'datetimeCreate': datetime.strptime(datetime_create, '%a, %d %b %Y %H:%M:%S %Z').strftime('%Y-%m-%d %H:%M:%S'),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not datetime.datetime
 ---- search_data_1
-------------------Log----------------24/04/22-16:51:01
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 2274, in search_data_5
    conn = pyodbc.connect('Driver={SQL Server}; Server=192.168.8.21; uid=sa; pwd=1234;Database=QC; Trusted_Connection=No;',timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC SQL Server Driver]Login timeout expired (0) (SQLDriverConnect)')
 ---- search_data_5
-------------------Log----------------24/04/22-16:51:01
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 1776, in search_data_1
    conn = pyodbc.connect('Driver={SQL Server}; Server=192.168.8.21; uid=sa; pwd=1234;Database=QC; Trusted_Connection=No;',timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC SQL Server Driver]Login timeout expired (0) (SQLDriverConnect)')
 ---- search_data_1
-------------------Log----------------24/04/22-16:51:01
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 2172, in search_data_4
    conn = pyodbc.connect('Driver={SQL Server}; Server=192.168.8.21; uid=sa; pwd=1234;Database=QC; Trusted_Connection=No;',timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC SQL Server Driver]Login timeout expired (0) (SQLDriverConnect)')
 ---- search_data_4
-------------------Log----------------24/04/22-16:51:01
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 2379, in search_data_6
    conn = pyodbc.connect('Driver={SQL Server}; Server=192.168.8.21; uid=sa; pwd=1234;Database=QC; Trusted_Connection=No;',timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC SQL Server Driver]Login timeout expired (0) (SQLDriverConnect)')
 ---- search_data_6
-------------------Log----------------24/04/22-16:51:01
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 1909, in search_data_2
    conn = pyodbc.connect('Driver={SQL Server}; Server=192.168.8.21; uid=sa; pwd=1234;Database=QC; Trusted_Connection=No;',timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC SQL Server Driver]Login timeout expired (0) (SQLDriverConnect)')
 ---- search_data_2