-------------------Log----------------24/05/08-10:43:34
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\users.py", line 207, in users_infor
    conn = pyodbc.connect('Driver={SQL Server}; Server=192.168.8.21; uid=sa; pwd=1234; Database=QC; Trusted_Connection=No;', timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC SQL Server Driver]Login timeout expired (0) (SQLDriverConnect)')
 ---- get_users_infor
-------------------Log----------------24/05/08-12:58:40
Traceback (most recent call last):
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexes\range.py", line 413, in get_loc
    return self._range.index(new_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 0 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 4169, in get_2dimage_thread_verification
    dmc = threadverification_2d.loc[0,"Product_type"]
        ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexing.py", line 1183, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4209, in _get_value
    row = self.index.get_loc(index)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexes\range.py", line 415, in get_loc
    raise KeyError(key) from err
KeyError: 0
 ---- get_2dimage_thread_verification
-------------------Log----------------24/05/08-15:21:26
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data
-------------------Log----------------24/05/08-15:21:27
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data
-------------------Log----------------24/05/08-15:21:28
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data
-------------------Log----------------24/05/08-15:21:29
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data
-------------------Log----------------24/05/08-15:21:30
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data
-------------------Log----------------24/05/08-15:21:31
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data
-------------------Log----------------24/05/08-15:21:32
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data
-------------------Log----------------24/05/08-15:21:33
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data
-------------------Log----------------24/05/08-15:21:34
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data
-------------------Log----------------24/05/08-15:21:35
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data
-------------------Log----------------24/05/08-15:21:36
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data
-------------------Log----------------24/05/08-15:21:37
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data
-------------------Log----------------24/05/08-15:21:42
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data
-------------------Log----------------24/05/08-15:21:47
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data
-------------------Log----------------24/05/08-15:21:52
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data
-------------------Log----------------24/05/08-15:21:57
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data
-------------------Log----------------24/05/08-15:22:02
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data
-------------------Log----------------24/05/08-15:22:07
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\WEB_DATA_API\products.py", line 3951, in get_thread_verification_data
    day_start = request.json['dayStart']
                ^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\wrappers.py", line 130, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vcast-Server\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
 ---- thread_verification_data